# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('profesor', models.CharField(max_length=60)),
                ('CURSOS', models.ManyToManyField(through='finals.Asignacion', to='finals.Estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='asignacion',
            name='Estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finals.Estudiante'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='Materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finals.Materia'),
        ),
    ]
